name: BO4IO
channels:
  - plotly
  - gurobi
  - gpytorch
  - anaconda
  - pytorch
  - conda-forge
  - https://conda.anaconda.org/gurobi
  - http://conda.anaconda.org/gurobi
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ampl-mp=3.1.0
  - blas=1.1
  - botorch=0.8.2
  - bottleneck=1.3.5
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.0
  - colorama=0.4.6
  - cycler=0.11.0
  - et_xmlfile=1.1.0
  - freetype=2.10.4
  - future=0.18.3
  - glpk=5.0
  - gmp=6.2.1
  - gpytorch=1.9.1
  - gurobi=10.0.1
  - ipopt=3.14.5
  - joblib=1.2.0
  - jpeg=9e
  - kiwisolver=1.4.4
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libgomp=11.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtiff=4.0.10
  - linear_operator=0.3.0
  - lz4-c=1.9.3
  - matplotlib-base=3.4.3
  - metis=5.1.0
  - multipledispatch=0.6.0
  - mumps-include=5.2.1
  - mumps-seq=5.2.1
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numexpr=2.8.4
  - numpy=1.22.3
  - olefile=0.46
  - openblas=0.3.20
  - openpyxl=3.0.10
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=23.0
  - patsy=0.5.3
  - pillow=6.2.1
  - pip=23.0.1
  - plotly=5.14.1
  - pycparser=2.21
  - pyparsing=3.0.9
  - pyro-api=0.1.2
  - pyro-ppl=1.8.4
  - python=3.8.16
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=1.12.1
  - pytz=2022.7.1
  - pyyaml=6.0
  - readline=8.2
  - scikit-learn=1.0.2
  - scipy=1.8.1
  - scotch=6.0.9
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - statsmodels=0.13.5
  - tenacity=8.0.1
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.65.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - unixodbc=2.3.10
  - wheel=0.38.4
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
    - anyio==3.6.2
    - appdirs==1.4.4
    - cobra==0.26.2
    - depinfo==1.7.0
    - diskcache==5.4.0
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - idna==3.4
    - importlib-resources==5.12.0
    - markdown-it-py==2.2.0
    - mdurl==0.1.2
    - mpmath==1.3.0
    - optlang==1.6.1
    - pandas==1.5.3
    - ply==3.11
    - pydantic==1.10.6
    - pygments==2.14.0
    - python-libsbml==5.19.7
    - rfc3986==1.5.0
    - rich==13.3.2
    - ruamel-yaml==0.17.21
    - ruamel-yaml-clib==0.2.7
    - sniffio==1.3.0
    - swiglpk==5.0.8
    - sympy==1.11.1
    - zipp==3.15.0
